apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dihac-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
  - hosts:
    - api.dihac.com
    secretName: dihac-tls
  rules:
  - host: api.dihac.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dihac-api-gateway
            port:
              number: 80

